#!/bin/bash

# Listing all documents to generate
for dir in $(ls src); do
	# Entering to each document's root
	pushd src/$dir &>/dev/null
	# Cleaning and building
	make
	# Move any figures (img/*.eps) that could be included
	cp -rf src/img ../../pdf 2>/dev/null
	# Copying the generated document to the final directory
	cp build/main.dvi ../../pdf/${dir}.dvi
	# Returning to the base dir
	popd &>/dev/null
done

# DVI to PDF
pushd pdf &>/dev/null
for doc in $(ls | grep -i .dvi); do
	dvipdf $doc
done
# Removing dependencies
rm -rf img
rm -f *.dvi
popd &>/dev/null
