name: demo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

concurrency:
  group: app
  cancel-in-progress: true

defaults:
  run:
    working-directory: 'src/app'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: node-setup
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
          cache-dependency-path: src/app/package-lock.json
      - name: install-dependencies
        run: npm i --no-audit --no-fund --no-optional
      - name: lint
        run: npm run eslint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: node-setup
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
          cache-dependency-path: src/app/package-lock.json
      - name: install-dependencies
        run: npm i --no-audit --no-fund --no-optional
      - name: build
        run: npm run build
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: src/app/dist
  test:
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: node-setup
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
          cache-dependency-path: src/app/package-lock.json
      - name: install-dependencies
        run: npm i --no-audit --no-fund --no-optional
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: src/app/dist
      - name: test
        run: npm test
  e2e:
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: node-setup
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
          cache-dependency-path: src/app/package-lock.json
      - name: install-dependencies
        run: npm i --no-audit --no-fund --no-optional
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: src/app/dist
      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          working-directory: src/app
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000
  containerize:
    if: ${{ github.event_name == 'push' }}
    needs:
      - lint
      - build
      - test
      - e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          sudo apt update
          sudo apt install -y buildah
      - name: build-image
        run: ./build.sh
      - name: push-to-registry
        run: |
          buildah push                                                             \
            --creds ${{ secrets.DOCKER_HUB_USER }}:${{ secrets.DOCKER_HUB_TOKEN }} \
            $IMAGE_NAME                                                            \
            docker://${{ secrets.DOCKER_HUB_USER }}/$APP
