name: documentation

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pdf:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          apt update && apt install -y poppler-utils ghostscript texinfo
      - name: build
        run: |
          make pdf
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: pronghorn-thesis
          path: pronghorn-*.pdf
  deploy:
    runs-on: ubuntu-latest
    container: texlive/texlive
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          apt update && apt install -y poppler-utils ghostscript texinfo
      - name: build
        run: |
          make html
          ls -la
      - name: configure-pages
        uses: actions/configure-pages@v3
      - name: upload-pages-artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: pronghorn.html
      - name: deploy-pages
        id: deployment
        uses: actions/deploy-pages@v2