name: documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pdf:
    if: ${{ github.event_name == 'push' ||
            github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs/') }}
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          apt update
          apt install -y poppler-utils ghostscript texinfo
      - name: build
        run: make pdf
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: pronghorn-paper-pdf
          path: pronghorn-*.pdf
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    container: texlive/texlive
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          apt update
          apt install -y poppler-utils ghostscript texinfo
      - name: build
        run: make html
      - name: configure-pages
        uses: actions/configure-pages@v3
      - name: upload-pages-artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: pronghorn.html
      - name: deploy-pages
        id: deployment
        uses: actions/deploy-pages@v2
